### ISSUE TITLE
Data indicators

### ISSUE THREAD

**Issue by MiaoZhenLian** [mtailanian/uflow#1]
May I ask if the indicators imageAUROC, pixel AUROC, and pixel AP in your paper were tested with the same or different weights?

**Comment by mtailanian** [comment]
Sorry for the delay; I completely missed this message. 
The final figures come from different checkpoints, although all the trainings were done always with the same parameters. 
I think the differences are in when to end the training, like an early stopping optimizing different metrics (which is what is actually done).
All checkpoints can be downloaded from the links posted and following the readme.
Anyways, using only one ckpt for each category leads to very similar results!
