### ISSUE TITLE
Aupro Checkpoint Missing

### ISSUE THREAD

**Issue by vmiller987** [mtailanian/uflow#3]
First, I greatly appreciate your work. It is written well and so far has been easily reproducible. 

I have been following the directions and commands to replicate the carpet dataset.

When I run `python src/train.py -cat carpet` this generates checkpoints only for auroc and miou. The aupro checkpoint is missing. This can also be seen in train.py under callbacks, there is only one for AuROC and mIoU. 

This becomes an issue when I try to run `python src/evaluate.py -cat carpet` as the `/models/pro/carpet.ckpt` file is missing. I have downloaded the pre-trained models, which then allow me to run this command.

However, I am wanting to adapt your model to my dataset. Currently, I will have to edit the evaluate.py section to exclude this to make it work, or I will need to add an aupro checkpoint. (I have not gotten this far yet, but I plan on working on this today.) 

Is there something I am missing or doing wrong?
My next steps are to adapt your work to accept other datasets.

**Comment by mtailanian** [comment]
Hello @vmiller987 
Thanks for pointing this out

I just updated the code, adding the aupro checkpoint saving. Just added a callback to track the metric, and used it in `train.py`.
